// Checkout test mode. Lets specific companies check out with a cheap Whop plan so the
// real payment -> webhook -> activation flow can be tested without paying full price.
//
// Set both in the server environment:
//   WHOP_TEST_PLAN_ID     the Whop plan to charge instead (starts with "plan_")
//   WHOP_TEST_COMPANY_ID  company id(s) that use it; separate several with commas
//
// Every other company is unaffected. Remove either setting to switch test mode off.
// Kept out of whop-config.ts because that file is regenerated by the setup script.
export function getTestPlanOverride(companyId: string): string | undefined {
  const planId = process.env.WHOP_TEST_PLAN_ID?.trim();
  if (!planId) return undefined;

  const testCompanyIds = (process.env.WHOP_TEST_COMPANY_ID ?? '')
    .split(',')
    .map((id) => id.trim().toLowerCase())
    .filter(Boolean);

  if (!testCompanyIds.includes(companyId.toLowerCase())) return undefined;

  console.warn(`[whop-test-mode] company ${companyId} is checking out with test plan ${planId}`);
  return planId;
}
