// TEMPORARY checkout test mode. Companies listed here check out with a cheap Whop plan
// instead of their real one, so the real payment -> webhook -> activation flow can be
// tested without paying full price. Every other company is unaffected.
//
// To switch it off after testing, empty TEST_COMPANY_IDS (or delete this file and the
// two getTestPlanOverride calls in the billing routes).
// Kept out of whop-config.ts because that file is regenerated by the setup script.
const TEST_PLAN_ID = 'plan_JwkLysuPK1ibX';
const TEST_COMPANY_IDS: string[] = ['0f067a92-908b-4271-b861-3fddccbc4b1b'];

export function getTestPlanOverride(companyId: string): string | undefined {
  if (!TEST_COMPANY_IDS.includes(companyId.toLowerCase())) return undefined;

  console.warn(`[whop-test-mode] company ${companyId} is checking out with test plan ${TEST_PLAN_ID}`);
  return TEST_PLAN_ID;
}
